spring.main.web-application-type=reactive

policy.timeout-by-range[0].min=0
policy.timeout-by-range[0].max=99
policy.timeout-by-range[0].timeout-ms=400
policy.timeout-by-range[1].min=100
policy.timeout-by-range[1].max=499
policy.timeout-by-range[1].timeout-ms=700
policy.timeout-by-range[2].min=500
policy.timeout-by-range[2].max=999999
policy.timeout-by-range[2].timeout-ms=800

policy.fallback-by-range[0].min=0
policy.fallback-by-range[0].max=99
policy.fallback-by-range[0].default-result=DEFAULT_LOW
policy.fallback-by-range[1].min=100
policy.fallback-by-range[1].max=499
policy.fallback-by-range[1].default-result=DEFAULT_MED
policy.fallback-by-range[2].min=500
policy.fallback-by-range[2].max=999999
policy.fallback-by-range[2].default-result=DEFAULT_HIGH

logging.topic.enabled=true

