spring.config.import=optional:consul:
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.refresh.enabled=true

spring.profiles.active=poc-loom
server.port=8080

external.base-url=http://localhost:8081
